import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

DATASET_DIR = os.path.join(BASE_DIR, "dataset", "freiburg_groceries")
SPLITS_DIR = os.path.join(BASE_DIR, "dataset", "splits") 
TEST_IMAGES_DIR = os.path.join(BASE_DIR, "images") 
OUTPUT_DIR = os.path.join(BASE_DIR, "output") 
MODELS_DIR = os.path.join(BASE_DIR, "models") 
REPORT_DIR = os.path.join(BASE_DIR, "report") 

MODEL_PATH = os.path.join(MODELS_DIR, "mobilenetv2_freiburg.keras")
CLASS_INDEX_PATH = os.path.join(MODELS_DIR, "class_indices.json")
CROPS_DIR = os.path.join(OUTPUT_DIR, "crops")

CLASS_NAMES = [
    "BEANS", "CAKE", "CANDY", "CEREAL", "CHIPS", "CHOCOLATE", "COFFEE",
    "CORN", "FISH", "FLOUR", "HONEY", "JAM", "JUICE", "MILK", "NUTS",
    "OIL", "PASTA", "RICE", "SODA", "SPICES", "SUGAR", "TEA",
    "TOMATO_SAUCE", "VINEGAR", "WATER",
]
NUM_CLASSES = len(CLASS_NAMES)

TRAIN_SPLIT = 0.70
VAL_SPLIT = 0.15
TEST_SPLIT = 0.15
RANDOM_SEED = 42

CLASSIFIER_IMG_SIZE = (224, 224)
CLASSIFIER_BATCH_SIZE = 32
CLASSIFIER_EPOCHS_HEAD = 15 
CLASSIFIER_EPOCHS_FINE_TUNE = 20 

CLASSIFIER_LEARNING_RATE = 1e-3
FINE_TUNE_LEARNING_RATE = 3e-5 
FINE_TUNE_WEIGHT_DECAY = 1e-2 
FINE_TUNE_AT_LAYER = 100   
USE_CLASS_WEIGHT = False 
OVERSAMPLE_MINORITY_CLASSES = True 
LABEL_SMOOTHING = 0.1 
CLASSIFICATION_CONFIDENCE_THRESHOLD = 0.5
CLASSIFIER_EARLY_STOPPING_PATIENCE = 4 
USE_DATA_AUGMENTATION = True  
USE_MIXUP = True 
MIXUP_ALPHA = 0.2 