import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

DATASET_DIR = os.path.join(BASE_DIR, "dataset", "freiburg_groceries")
SPLITS_DIR = os.path.join(BASE_DIR, "dataset", "splits") 
TEST_IMAGES_DIR = os.path.join(BASE_DIR, "images") 
OUTPUT_DIR = os.path.join(BASE_DIR, "output") 
MODELS_DIR = os.path.join(BASE_DIR, "models") 
REPORT_DIR = os.path.join(BASE_DIR, "report") 

MODEL_PATH = os.path.join(MODELS_DIR, "mobilenetv2_freiburg.keras")
CLASS_INDEX_PATH = os.path.join(MODELS_DIR, "class_indices.json")
CROPS_DIR = os.path.join(OUTPUT_DIR, "crops")

CLASS_NAMES = [
    "BEANS", "CAKE", "CANDY", "CEREAL", "CHIPS", "CHOCOLATE", "COFFEE",
    "CORN", "FISH", "FLOUR", "HONEY", "JAM", "JUICE", "MILK", "NUTS",
    "OIL", "PASTA", "RICE", "SODA", "SPICES", "SUGAR", "TEA",
    "TOMATO_SAUCE", "VINEGAR", "WATER",
]
NUM_CLASSES = len(CLASS_NAMES)

TRAIN_SPLIT = 0.70
VAL_SPLIT = 0.15
TEST_SPLIT = 0.15
RANDOM_SEED = 42

CLASSIFIER_IMG_SIZE = (224, 224)
CLASSIFIER_BATCH_SIZE = 32
CLASSIFIER_EPOCHS_HEAD = 15 
CLASSIFIER_EPOCHS_FINE_TUNE = 20 

CLASSIFIER_LEARNING_RATE = 1e-3
FINE_TUNE_LEARNING_RATE = 3e-5 
FINE_TUNE_WEIGHT_DECAY = 1e-2 
FINE_TUNE_AT_LAYER = 100   
USE_CLASS_WEIGHT = False 
OVERSAMPLE_MINORITY_CLASSES = True 
LABEL_SMOOTHING = 0.1 
CLASSIFICATION_CONFIDENCE_THRESHOLD = 0.5
CLASSIFIER_EARLY_STOPPING_PATIENCE = 4 
USE_DATA_AUGMENTATION = True  
USE_MIXUP = True 
MIXUP_ALPHA = 0.2 

PREPROCESS_RESIZE_WIDTH = 800 
GAUSSIAN_KERNEL_SIZE = (5, 5) 
GAUSSIAN_SIGMA = 0
ADAPTIVE_THRESH_BLOCK_SIZE = 21 
ADAPTIVE_THRESH_C = 5
THRESHOLD_METHOD = "adaptive"
BINARY_THRESH_VALUE = 127
THRESHOLD_INVERT = True
CANNY_LOW_THRESHOLD = 50
CANNY_HIGH_THRESHOLD = 150
MORPH_KERNEL_SIZE = (5, 5)
MORPH_ITERATIONS = 2

MIN_CONTOUR_AREA = 1500 
BOUNDING_BOX_COLOR = (0, 255, 0) 
BOUNDING_BOX_THICKNESS = 2
LABEL_FONT = "FONT_HERSHEY_SIMPLEX"
LABEL_FONT_SCALE = 0.6
LABEL_COLOR = (0, 255, 0)
LABEL_THICKNESS = 2

SHOW_PLOTS = True 
SAVE_INTERMEDIATE_STEPS = True